# Generated by Django 5.0.6 on 2024-08-31 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBapp', '0003_register_delete_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Conf_password',
        ),
    ]
