# Generated by Django 5.0.6 on 2024-08-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBapp', '0004_remove_register_conf_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Password',
            field=models.CharField(max_length=100),
        ),
    ]
